### ISSUE TITLE
Hello From GitHub

### ISSUE THREAD

**Issue by hamelsmu** [dslp/dslp#19]
We are working on [mlops](https://mlops-github.com).  Maybe we should be in touch

**Comment by charleswm** [comment]
I agree. I'm familiar with the work you're all doing on the GitHub MLOps side. It's really awesome and definitely aligned to the goals of this project. (Build repeatable processes to make data science more successful on average)

**Comment by hamelsmu** [comment]
Cool will close this issue and continue the conversation
