### ISSUE TITLE
mlflow project files 

### ISSUE THREAD

**Issue by lostmygithubaccount** [dslp/dslp#23]
where should mlflow project files be placed? we are expecting to have many of them

**Comment by charleswm** [comment]
Good question. I'd say it would either go in pipelines or get its own directory at the root level.  My knee-jerk reaction would be the latter. Thoughts?

**Comment by lostmygithubaccount** [comment]
I think own directory at the root level as well - I initially had it in code but I don't think that or pipelines really makes sense

**Comment by charleswm** [comment]
@lostmygithubaccount 

I agree. Code is for your core code and logic, not your glue/metadata scripts. And pipelines is basically for defining dags (azureml, airflow, etc).

I opened a PR adding an "optional directories" section to the default directory docs. See #24.

I don't think mlflow could be considered a "default" at this point, but I definitely see it being common enough to warrant a callout. Do you think that's enough or should we do more here?

**Comment by lostmygithubaccount** [comment]
I would name the directory "mlprojects" instead of "mlflow"
